// Tests for lesson_12 & lesson_13

pipeline {
    agent any

    options {
        timestamps()
        timeout(time: 20, unit: 'MINUTES')
    }

    triggers {
        pollSCM('H/2 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {

                checkout scm
            }
        }

        stage('Install system deps') {
            steps {

                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip python3-venv
                '''
            }
        }

        stage('Install requirements') {
            steps {
                sh '''
                    python3 -m venv .venv-ci
                    . .venv-ci/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements-ci.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    . .venv-ci/bin/activate
                    pytest lesson_12 lesson_13 -v --alluredir=allure-results --junitxml=junit.xml
                '''
            }
        }
    }

    post {
        always {

            junit allowEmptyResults: true, testResults: 'junit.xml'
            allure includeProperties: false, results: [[path: 'allure-results']]
        }

        //
        failure {
            mail to: 'o.zhalii_mail@mailinator.com',
                 subject: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Build: ${env.BUILD_URL}"
        }
        success {
            mail to: 'o.zhalii_mail@mailinator.com',
                 subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Build: ${env.BUILD_URL}"
        }
    }
}